// Inlines the @modelcontextprotocol/ext-apps browser bundle into the widget HTML at
// build time and emits a TS string constant. Required because Cloudflare Workers has no
// runtime filesystem — the host iframe also blocks CDN imports, so the bundle must be
// spliced into the HTML before the worker serves it as a UI resource.
//
// Run: node scripts/build-widget.mjs  (wired into `predev` / `deploy` in package.json)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// 1. ext-apps browser bundle → rewrite trailing `export{a as App,...}` to globalThis.ExtApps.
const bundleSrc = readFileSync(
  require.resolve("@modelcontextprotocol/ext-apps/app-with-deps"),
  "utf8",
);
let rewrote = false;
const bundle = bundleSrc.replace(/export\{([^}]+)\};?\s*$/, (_, body) => {
  rewrote = true;
  const members = body
    .split(",")
    .map((p) => {
      const [local, exported] = p.split(" as ").map((s) => s.trim());
      return `${exported ?? local}:${local}`;
    })
    .join(",");
  return `globalThis.ExtApps={${members}};`;
});
if (!rewrote) {
  throw new Error("build-widget: could not find trailing `export{...}` in app-with-deps bundle");
}

// 2. Splice the bundle into the widget HTML placeholder.
const htmlPath = resolve(repoRoot, "widgets/dashboard.html");
const html = readFileSync(htmlPath, "utf8");
const PLACEHOLDER = "/*__EXT_APPS_BUNDLE__*/";
if (!html.includes(PLACEHOLDER)) {
  throw new Error(`build-widget: placeholder ${PLACEHOLDER} not found in ${htmlPath}`);
}
// Use a function replacer so `$` sequences in the bundle aren't treated as replacement patterns.
const inlined = html.replace(PLACEHOLDER, () => bundle);

// 3. Emit the generated TS module (JSON.stringify handles all escaping).
const outDir = resolve(repoRoot, "src/widgets");
mkdirSync(outDir, { recursive: true });
const outPath = resolve(outDir, "dashboard.generated.ts");
writeFileSync(
  outPath,
  "// GENERATED by scripts/build-widget.mjs — do not edit. Source: widgets/dashboard.html\n" +
    `export const DASHBOARD_HTML = ${JSON.stringify(inlined)};\n`,
);

console.log(`build-widget: wrote ${outPath} (${inlined.length} bytes inlined)`);
